[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaac_quad_sim2real"
readme  = "README.md"

title = "ISAAC_QUAD_SIM2REAL"
author = "Lorenzo Bianchi"
maintainer = "Lorenzo Bianchi"
description = "IsaacLab extension to develop RL environments for drones"
repository = "https://github.com/Jirl-upenn/isaac_quad_sim2real"
keywords = ["extension", "template", "isaaclab"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "isaac_quad_sim2real"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
